#!/bin/bash
set -e

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
cd "$SCRIPT_DIR"

echo ""
echo "  ╔══════════════════════════════════════════╗"
echo "  ║      BugBountyTool — Installer           ║"
echo "  ║      by Hacker00X1                       ║"
echo "  ╚══════════════════════════════════════════╝"
echo ""

echo "[*] Installing Python dependencies..."
pip install -r requirements.txt --quiet

echo ""
echo "[✓] Installation complete!"
echo ""
echo "  Structure:"
echo "    toolkit.py     — Interactive menu (start here)"
echo "    bb.py          — Full CLI scanner"
echo "    data/          — All scanning modules"
echo "    wordlists/     — Subdomain, directory, parameter wordlists"
echo "    reports/       — Scan reports (HTML + JSON)"
echo ""
echo "  Usage:"
echo "    python toolkit.py                          # Interactive menu launcher"
echo "    python toolkit.py -t example.com           # Pre-set target"
echo "    python bb.py <target>                      # Full scan (CLI)"
echo "    python bb.py example.com                   # Scan a domain"
echo "    python bb.py https://example.com           # Scan a URL"
echo "    python bb.py example.com --ports extended  # Extended port scan"
echo "    python bb.py example.com --skip-ports      # Skip port scan"
echo "    python bb.py example.com --skip-owasp      # Skip OWASP Top 10 module"
echo "    python bb.py example.com -o /tmp/reports   # Custom report dir"
echo "    python bb.py example.com --threads 40      # Custom threading"
echo "    python bb.py --help                        # Show all options"
echo ""
echo "  OWASP Top 10 (toolkit menu items 17-25):"
echo "    17 — A01 Broken Access Control"
echo "    18 — A02 Cryptographic Failures"
echo "    19 — A05 Security Misconfiguration"
echo "    20 — A06 Outdated Components"
echo "    21 — A07 Auth Failures"
echo "    22 — A08 Integrity Failures"
echo "    23 — A09 Logging Failures"
echo "    24 — A10 SSRF"
echo "    25 — Full OWASP Top 10 Scan"
echo "    31 — OWASP-only preset scan"
echo ""
echo "  Reports are saved to: ./reports/"
echo ""
