'''
╭──────────────────────────────────────────────────────────────────────────────╮
│  ██╗  ██╗ █████╗  ██████╗██╗  ██╗███████╗██████╗  ██████╗  ██████╗ ██╗  ██╗ ██╗  
│  ██║  ██║██╔══██╗██╔════╝██║ ██╔╝██╔════╝██╔══██╗██╔═══██╗██╔═══██╗╚██╗██╔╝███║  
│  ███████║███████║██║     █████╔╝ █████╗  ██████╔╝██║   ██║██║   ██║ ╚███╔╝  ██║  
│  ██╔══██║██╔══██║██║     ██╔═██╗ ██╔══╝  ██╔══██╗██║   ██║██║   ██║ ██╔██╗  ██║  
│  ██║  ██║██║  ██║╚██████╗██║  ██╗███████╗██║  ██║╚██████╔╝╚██████╔╝██╔╝ ██╗ ██║  
│  ╚═╝  ╚═╝╚═╝  ╚═╝ ╚═════╝╚═╝  ╚═╝╚══════╝╚═╝  ╚═╝ ╚═════╝  ╚═════╝╚═╝  ╚═╝ ╚═╝  
│                                                                              
│    Bug Bounty Tool Kit  ─  Recon · Scan · Exploit · Report                  
╰── Only scan targets you own or have explicit written permission to test ─────╯
'''

"""
WAF / rate-limit fingerprinter.

Sends a series of probe requests (clean, suspicious, malicious) and
analyses response headers, status codes, and body content to identify
the protection layer in front of the target.

Also probes for rate-limiting by firing a burst of rapid requests and
watching for 429 / 503 responses.

Returns a structured result the scanner uses to auto-tune thread count
and crawl delay for the rest of the scan.
"""

import time
import urllib.parse
import urllib.request
import urllib.error
from concurrent.futures import ThreadPoolExecutor, as_completed
from typing import Optional


# ── WAF signatures ────────────────────────────────────────────────────────────
# Each entry: (name, matchers)
# matchers: list of (field, pattern) where field is one of:
#   "header:<name>"  – response header value (lower-cased)
#   "body"           – response body (lower-cased, first 8 KB)
#   "status"         – string of the HTTP status code
#   "server"         – Server header value

WAF_SIGNATURES: list[tuple[str, list[tuple[str, str]]]] = [
    ("Cloudflare", [
        ("header:server",                "cloudflare"),
        ("header:cf-ray",                ""),
        ("header:cf-cache-status",       ""),
        ("body",                         "cloudflare ray id"),
        ("body",                         "attention required! | cloudflare"),
    ]),
    ("AWS WAF", [
        ("header:x-amzn-requestid",      ""),
        ("header:x-amz-cf-id",           ""),
        ("body",                         "aws waf"),
        ("body",                         "request blocked"),
    ]),
    ("Akamai", [
        ("header:x-check-cacheable",     ""),
        ("header:x-akamai-transformed",  ""),
        ("header:akamai-origin-hop",     ""),
        ("body",                         "the requested url was rejected. please consult with your administrator."),
        ("body",                         "reference #"),
    ]),
    ("Imperva / Incapsula", [
        ("header:x-iinfo",               ""),
        ("header:incap-ses",             ""),
        ("header:visid-incap",           ""),
        ("body",                         "incapsula incident id"),
        ("body",                         "_incapsula_resource"),
    ]),
    ("ModSecurity", [
        ("header:server",                "mod_security"),
        ("body",                         "mod_security"),
        ("body",                         "this error was generated by mod_security"),
        ("body",                         "406 not acceptable"),
    ]),
    ("Sucuri", [
        ("header:x-sucuri-id",           ""),
        ("header:x-sucuri-cache",        ""),
        ("body",                         "sucuri website firewall"),
        ("body",                         "sucuri cloudproxy"),
        ("body",                         "access denied - sucuri website firewall"),
    ]),
    ("F5 BIG-IP ASM", [
        ("header:x-cnection",            "close"),
        ("header:set-cookie",            "ts"),
        ("body",                         "the requested url was rejected"),
        ("body",                         "f5 networks"),
        ("body",                         "support id"),
    ]),
    ("Barracuda", [
        ("header:x-barracuda-connect",   ""),
        ("body",                         "barracuda"),
        ("body",                         "bwf-block"),
        ("body",                         "barracuda web application firewall"),
    ]),
    ("Wordfence", [
        ("body",                         "generated by wordfence"),
        ("body",                         "your access to this site has been limited"),
        ("body",                         "wordfence"),
    ]),
    ("Fortinet FortiWeb", [
        ("header:set-cookie",            "fortiwafsid"),
        ("body",                         "fortiwaf"),
        ("body",                         "fortigate"),
    ]),
    ("Radware AppWall", [
        ("header:x-sid",                 ""),
        ("body",                         "unauthorized activity has been detected"),
        ("body",                         "rdwr"),
    ]),
    ("Citrix NetScaler / AAA", [
        ("header:via",                   "ns-cache"),
        ("header:set-cookie",            "nstx"),
        ("header:set-cookie",            "nsglobal"),
        ("body",                         "netscaler"),
        ("body",                         "citrix"),
    ]),
    ("Reblaze", [
        ("header:x-reblaze-protection",  ""),
        ("header:set-cookie",            "rbzid"),
        ("body",                         "reblaze"),
    ]),
    ("PerimeterX", [
        ("header:x-px-enforcer-telemetry", ""),
        ("body",                         "perimeterx"),
        ("body",                         "_pxhd"),
    ]),
    ("DataDome", [
        ("header:x-datadome",            ""),
        ("header:set-cookie",            "datadome"),
        ("body",                         "datadome"),
    ]),
    ("Fastly CDN", [
        ("header:x-fastly-request-id",   ""),
        ("header:x-served-by",           "cache"),
        ("header:fastly-restarts",       ""),
    ]),
    ("Varnish Cache", [
        ("header:x-varnish",             ""),
        ("header:via",                   "varnish"),
        ("body",                         "varnish cache server"),
    ]),
    ("DenyAll", [
        ("header:set-cookie",            "sessioncookie"),
        ("body",                         "denyall"),
        ("body",                         "deny all"),
    ]),
    ("Nginx rate limit", [
        ("status",                       "429"),
        ("body",                         "nginx"),
        ("body",                         "rate limit exceeded"),
    ]),
    ("Cloudfront (AWS CDN)", [
        ("header:x-amz-cf-pop",          ""),
        ("header:x-amz-cf-id",           ""),
        ("body",                         "error from cloudfront"),
    ]),
]


# ── Probe payloads ────────────────────────────────────────────────────────────

CLEAN_PROBE   = "/"

ATTACK_PROBES = [
    "/?id=1'%20OR%20'1'='1",                      # SQLi
    "/?q=<script>alert(1)</script>",               # XSS
    "/?file=../../../../etc/passwd",               # LFI
    "/?url=https://evil.com",                      # Open redirect
    "/?search=UNION+SELECT+NULL,NULL,NULL--",      # SQLi union
]


# ── HTTP helpers ──────────────────────────────────────────────────────────────

def _request(url: str, timeout: int, user_agent: str) -> Optional[dict]:
    try:
        req = urllib.request.Request(
            url,
            headers={"User-Agent": user_agent, "Accept": "*/*"},
        )
        with urllib.request.urlopen(req, timeout=timeout) as resp:
            headers = {k.lower(): v.lower() for k, v in resp.headers.items()}
            body    = resp.read(8192).decode("utf-8", errors="replace").lower()
            return {"status": str(resp.status), "headers": headers, "body": body, "url": url}
    except urllib.error.HTTPError as e:
        headers = {k.lower(): v.lower() for k, v in e.headers.items()}
        try:
            body = e.read(8192).decode("utf-8", errors="replace").lower()
        except Exception:
            body = ""
        return {"status": str(e.code), "headers": headers, "body": body, "url": url}
    except Exception:
        return None


def _match(response: dict, field: str, pattern: str) -> bool:
    if field.startswith("header:"):
        hdr_name = field[7:]
        hdr_val  = response["headers"].get(hdr_name, "")
        return pattern == "" or pattern in hdr_val
    elif field == "body":
        return pattern in response["body"]
    elif field == "status":
        return response["status"] == pattern
    elif field == "server":
        return pattern in response["headers"].get("server", "")
    return False


def _score_waf(name: str, matchers: list, responses: list[dict]) -> int:
    score = 0
    for resp in responses:
        for field, pattern in matchers:
            if _match(resp, field, pattern):
                score += 1
    return score


# ── Rate-limit probe ──────────────────────────────────────────────────────────

def _probe_rate_limit(base_url: str, timeout: int, user_agent: str, burst: int = 30) -> dict:
    """
    Fire `burst` rapid requests and count 429/503 responses.
    Returns: triggered (bool), first_block_at (int|None), pct_blocked (float)
    """
    statuses = []
    block_at = None

    def _fetch(i: int):
        resp = _request(base_url, timeout, user_agent)
        return (i, resp["status"] if resp else "err")

    with ThreadPoolExecutor(max_workers=burst) as executor:
        futures = {executor.submit(_fetch, i): i for i in range(burst)}
        for future in as_completed(futures):
            idx, status = future.result()
            statuses.append((idx, status))

    blocked = [(i, s) for i, s in statuses if s in ("429", "503")]
    triggered = len(blocked) > 0
    if blocked:
        block_at = min(i for i, _ in blocked)

    pct_blocked = len(blocked) / burst * 100 if burst else 0.0
    return {
        "triggered":       triggered,
        "burst_size":      burst,
        "blocked_count":   len(blocked),
        "first_block_at":  block_at,
        "pct_blocked":     round(pct_blocked, 1),
    }


# ── Tuning profiles ───────────────────────────────────────────────────────────

# For each known WAF: (recommended_threads, recommended_crawl_delay_ms, notes)
WAF_TUNING: dict[str, tuple[int, int, str]] = {
    "Cloudflare":            (5,  500,  "Aggressive fingerprinting; Cloudflare bot-score may ban IPs."),
    "AWS WAF":               (8,  300,  "Managed rules; lower thread count avoids triggering rate rules."),
    "Akamai":                (5,  600,  "Akamai bot detection is sensitive to request cadence."),
    "Imperva / Incapsula":   (5,  500,  "Incapsula tracks sessions; slow down to avoid CAPTCHA loops."),
    "ModSecurity":           (10, 200,  "Rule-based; attack probes will be blocked but recon is usually fine."),
    "Sucuri":                (8,  300,  "Sucuri blocks on threshold; moderate slow-down recommended."),
    "F5 BIG-IP ASM":         (6,  400,  "F5 behavioural analysis; reduce threads and add delay."),
    "Barracuda":             (8,  300,  "Rate-limit headers usually returned; respect them."),
    "Wordfence":             (10, 200,  "WordPress plugin; fairly lenient on recon requests."),
    "Fortinet FortiWeb":     (5,  500,  "Session-aware; reduce concurrency."),
    "Radware AppWall":       (5,  500,  "Behavioural WAF; high concurrency will trigger blocks."),
    "Citrix NetScaler / AAA":(8,  300,  "Cookie-based session tracking; moderate concurrency is safe."),
    "Reblaze":               (4,  600,  "ML-based; even recon can trigger challenges."),
    "PerimeterX":            (4,  700,  "JS-challenge heavy; most probes won't execute JS."),
    "DataDome":              (4,  700,  "ML bot management; very sensitive to automated patterns."),
    "Fastly CDN":            (15, 100,  "CDN only, no WAF signals; standard concurrency is fine."),
    "Varnish Cache":         (15, 100,  "Reverse proxy / cache; no WAF, normal concurrency."),
    "DenyAll":               (6,  400,  "Session-pinning WAF; reduce threads."),
    "Nginx rate limit":      (6,  400,  "Configured rate limit detected; respect it."),
    "Cloudfront (AWS CDN)":  (15, 100,  "CDN only; standard concurrency."),
}

DEFAULT_TUNING = (20, 0, "No WAF detected — using full concurrency.")


# ── Public API ────────────────────────────────────────────────────────────────

def fingerprint(
    base_url:   str,
    timeout:    int  = 8,
    user_agent: str  = "BugBountyTool/1.0",
    probe_attacks: bool = True,
) -> dict:
    """
    Fingerprint the WAF/CDN in front of base_url.

    Returns:
      detected          – list of {name, confidence, signals_matched}
      primary_waf       – name of the top match (or None)
      rate_limit        – rate-limit probe results
      recommended_threads  – int
      recommended_delay_ms – int
      notes             – str
      all_responses     – raw probe data (for report)
    """
    # 1. Collect probe responses
    probe_urls = [urllib.parse.urljoin(base_url, CLEAN_PROBE)]
    if probe_attacks:
        for path in ATTACK_PROBES:
            probe_urls.append(urllib.parse.urljoin(base_url, path))

    responses: list[dict] = []
    with ThreadPoolExecutor(max_workers=6) as executor:
        futures = [executor.submit(_request, u, timeout, user_agent) for u in probe_urls]
        for future in as_completed(futures):
            r = future.result()
            if r:
                responses.append(r)

    if not responses:
        return {
            "detected":             [],
            "primary_waf":          None,
            "rate_limit":           {},
            "recommended_threads":  DEFAULT_TUNING[0],
            "recommended_delay_ms": DEFAULT_TUNING[1],
            "notes":                "Could not reach target for WAF probing.",
            "probes_sent":          len(probe_urls),
        }

    # 2. Score each WAF signature
    scored: list[dict] = []
    for name, matchers in WAF_SIGNATURES:
        score = _score_waf(name, matchers, responses)
        if score > 0:
            total_signals = len(matchers)
            confidence    = min(100, round(score / max(total_signals, 1) * 100))
            scored.append({
                "name":            name,
                "score":           score,
                "signals_matched": score,
                "total_signals":   total_signals,
                "confidence":      confidence,
            })

    scored.sort(key=lambda x: x["score"], reverse=True)

    # 3. Collect interesting headers for the report
    header_set: dict[str, str] = {}
    for resp in responses:
        for k, v in resp["headers"].items():
            interesting = any(tok in k for tok in [
                "server", "x-", "cf-", "via", "set-cookie", "powered-by",
                "cache", "akamai", "fastly", "incap", "datadome",
            ])
            if interesting and k not in header_set:
                header_set[k] = v

    # 4. Rate-limit probe
    rl = _probe_rate_limit(base_url, timeout, user_agent)

    # 5. Recommended tuning
    primary = scored[0]["name"] if scored else None
    if primary and primary in WAF_TUNING:
        rec_threads, rec_delay, notes = WAF_TUNING[primary]
    else:
        rec_threads, rec_delay, notes = DEFAULT_TUNING

    if rl["triggered"] and rec_delay < 300:
        rec_delay = max(rec_delay, 400)
        notes += " Rate-limiting confirmed — crawl delay bumped."
    if rl["pct_blocked"] > 50:
        rec_threads = min(rec_threads, 5)
        notes += " High block rate — threads capped at 5."

    return {
        "detected":             scored,
        "primary_waf":          primary,
        "interesting_headers":  header_set,
        "rate_limit":           rl,
        "recommended_threads":  rec_threads,
        "recommended_delay_ms": rec_delay,
        "notes":                notes,
        "probes_sent":          len(probe_urls),
    }


if __name__ == "__main__":
    pass
